// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBEKiVJRJfN2UeNbk1dOegES3LBs0arKw',
    appId: '1:620311657206:web:d3ac93bd15c78850518ad7',
    messagingSenderId: '620311657206',
    projectId: 'news-app-ad41b',
    authDomain: 'news-app-ad41b.firebaseapp.com',
    storageBucket: 'news-app-ad41b.firebasestorage.app',
    measurementId: 'G-L2WZLZF66M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBna4WEk3Tv92hcCrpFk9UMY7xpU5eGsRo',
    appId: '1:620311657206:android:3c40f2fd5c8f6c93518ad7',
    messagingSenderId: '620311657206',
    projectId: 'news-app-ad41b',
    storageBucket: 'news-app-ad41b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBEKiVJRJfN2UeNbk1dOegES3LBs0arKw',
    appId: '1:620311657206:web:dee73c1389a7e93b518ad7',
    messagingSenderId: '620311657206',
    projectId: 'news-app-ad41b',
    authDomain: 'news-app-ad41b.firebaseapp.com',
    storageBucket: 'news-app-ad41b.firebasestorage.app',
    measurementId: 'G-YJNTG0DP85',
  );
}
